### ISSUE TITLE
one-to-one link hatasi

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus#107]
personel.Personel modeline, hitap.NufusKayitlari modelinden verilen one-to-one baglantida 

``` python
class NufusKayitlari(Model):
    ...
    sebep = field.Integer("Sebep", index=True)
    sync = field.Integer("Senkronize", index=True)
    personel = Personel(one_to_one=True)

    class Meta:
        app = 'Personel'
   ...
```

asagidaki hata donuyor. Nufus kayitlari her personel icin sadece bir tane.

``` python
Traceback (most recent call last):
  File "/Users/zops5/dev/zetaops/zengine/zengine/server.py", line 89, in on_post
    view(current, *args, **kwargs)
  File "/Users/zops5/dev/zetaops/ulakbus/ulakbus/views/system.py", line 73, in __init__
    self.do_search()
  File "/Users/zops5/dev/zetaops/ulakbus/ulakbus/views/system.py", line 82, in do_search
    for o in objects:
  File "/Users/zops5/dev/zetaops/pyoko/pyoko/db/base.py", line 142, in __iter__
    if self._cfg['rtype'] == ReturnType.Model else riak_obj)
  File "/Users/zops5/dev/zetaops/pyoko/pyoko/db/base.py", line 297, in _make_model
    return model.set_data(data, from_db=True)
  File "/Users/zops5/dev/zetaops/pyoko/pyoko/model.py", line 550, in set_data
    self._load_data(data, from_db)
  File "/Users/zops5/dev/zetaops/pyoko/pyoko/model.py", line 437, in _load_data
    self._instantiate_linked_models(self._data)
  File "/Users/zops5/dev/zetaops/pyoko/pyoko/model.py", line 302, in _instantiate_linked_models
    self.root.update_new_linked_model(linked_mdl_ins, name, o2o)
  File "/Users/zops5/dev/zetaops/pyoko/pyoko/model.py", line 602, in update_new_linked_model
    remote_name) in linked_mdl_ins._get_reverse_links():
AttributeError: 'dict' object has no attribute '_get_reverse_links'
```

Hata kimlik_ve_iletisim_bilgileri branchte tekrar edilebilir.

**Comment by evrenesat** [comment]
çözüm: `manage.py flush_model --model personel`

açıklama: NufusKayıtları daha önce personlin altındaki bir node olduğundan, ve mevcut veritabanında içinde NufusKayitlari'ni da içeren bir personel kaydı varolduğundan dolayı ortaya çıkıyor. _instantiate_linked_models metodu "data" argumanı için linked_model isimlerini arıyor ama bulduğu şeyin model instance ı olmasını bekliyor. beklediği gibi olmayınca da patlıyor...

bir daha olmaması için olayı şurda ele alacağız: zetaops/pyoko#24
