### ISSUE TITLE
Model kayderken riak hatasi

### ISSUE THREAD

**Issue by yetercatikkas** [zetaops/ulakbus#39]
Bi modele kayit eklerken iliskili diger model bos ise submit edilen form tmp ile baslayan bir deger ile gonderiliyor.Bu key riak olmadigi icin Exception: Returned empty data from Riak hatasini aliyoruz.

```
<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,166 - zengine.log - INFO - REQUEST DATA: {"form":{"akts_uygulama":2,"verilis_bicimi":44,"ad":"asdadfas","ders_dili":"tr","akts_teori":4,"kod":"234","program_id":"TMP_Program_4a80dd00cd","zorunlu":true,"kredi":"23","donem_id":"TMP_Program_681081f558"},"cmd":"add","subcmd":"do_list","model":"Ders","token":"81e138361f6c4fb4bea81f4a4efb47e7"}

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:REQUEST DATA: {"form":{"akts_uygulama":2,"verilis_bicimi":44,"ad":"asdadfas","ders_dili":"tr","akts_teori":4,"kod":"234","program_id":"TMP_Program_4a80dd00cd","zorunlu":true,"kredi":"23","donem_id":"TMP_Program_681081f558"},"cmd":"add","subcmd":"do_list","model":"Ders","token":"81e138361f6c4fb4bea81f4a4efb47e7"}

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,169 - zengine.log - INFO - TOKEN iNCOMiNG: 81e138361f6c4fb4bea81f4a4efb47e7 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:TOKEN iNCOMiNG: 81e138361f6c4fb4bea81f4a4efb47e7 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,175 - zengine.log - INFO - 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: WFCACHE: [u'"SequenceFlow_13", 1', {u'do': None, u'show': None, u'edit': None, u'cmd': u'add', u'list': None, u'update': None, u'object_id': None, u'add': True, u'IS_srlzd': {}, u'delete': None}]

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: WFCACHE: [u'"SequenceFlow_13", 1', {u'do': None, u'show': None, u'edit': None, u'cmd': u'add', u'list': None, u'update': None, u'object_id': None, u'add': True, u'IS_srlzd': {}, u'delete': None}]

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,182 - zengine.log - INFO - CHECK PERM: crud

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:CHECK PERM: crud

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,183 - zengine.log - INFO - REQUIRE PERM: crud

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:REQUIRE PERM: crud

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,184 - zengine.log - INFO - CHECK CRUD PERM: Ders.add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:CHECK CRUD PERM: Ders.add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,186 - zengine.log - INFO - ::::::::::: ENGINE STARTED :::::::::::

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   CMD:add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   SUBCMD:do_list

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:::::::::::: ENGINE STARTED :::::::::::

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   CMD:add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   SUBCMD:do_list

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,191 - zengine.log - INFO - CHECK PERM: crud.save_object

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:CHECK PERM: crud.save_object

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,192 - zengine.log - INFO - REQUIRE PERM: crud.save_object

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:REQUIRE PERM: crud.save_object

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,193 - zengine.log - INFO - CHECK CRUD PERM: Ders.add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:CHECK CRUD PERM: Ders.add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,194 - zengine.log - INFO - 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: - - - - - -

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: WORKFLOW: CRUD

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: TASK: save_object ( ServiceTask )

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: DATA:

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   IS: {}

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   cmd: add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   add: True

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: CURRENT:

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   ACTIVITY: crud_view

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   TOKEN: 81e138361f6c4fb4bea81f4a4efb47e7

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: = = = = = =

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: - - - - - -

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: WORKFLOW: CRUD

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: TASK: save_object ( ServiceTask )

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: DATA:

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   IS: {}

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   cmd: add

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   add: True

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: CURRENT:

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   ACTIVITY: crud_view

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   TOKEN: 81e138361f6c4fb4bea81f4a4efb47e7

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: = = = = = =

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,195 - zengine.log - INFO - CRUD CALL

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:CRUD CALL

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,196 - zengine.log - INFO - Calling add_view of Ders

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:Calling add_view of Ders

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: 2015-09-30 11:43:26,277 - zengine.log - INFO - RESPONSE: {"is_login": true}

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: INFO:zengine.log:RESPONSE: {"is_login": true}

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: [2015-09-30 11:43:26 +0000] [70] [ERROR] Error handling request

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: Traceback (most recent call last):

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 52, in handle

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self.handle_request(listener_name, req, client, addr)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 159, in handle_request

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     super(GeventWorker, self).handle_request(*args)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 105, in handle_request

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     respiter = self.wsgi(environ, resp.start_response)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/Beaker-1.7.0-py2.7.egg/beaker/middleware.py", line 155, in __call__

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     return self.wrap_app(environ, session_start_response)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/falcon-0.3.0-py2.7.egg/falcon/api.py", line 182, in __call__

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     responder(req, resp, **params)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/zengine-0.0.9-py2.7.egg/zengine/server.py", line 46, in on_post

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self.engine.run()

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/zengine-0.0.9-py2.7.egg/zengine/engine.py", line 307, in run

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self.run_activity()

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/zengine-0.0.9-py2.7.egg/zengine/engine.py", line 329, in run_activity

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self.workflow_methods[self.current.activity](self.current)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/zengine-0.0.9-py2.7.egg/zengine/views/crud.py", line 51, in __call__

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self.__class__.__dict__['%s_view' % (self.cmd or 'list')](self)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/zengine-0.0.9-py2.7.egg/zengine/views/crud.py", line 129, in add_view

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self._save_object()

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/zengine-0.0.9-py2.7.egg/zengine/views/crud.py", line 138, in _save_object

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self.object = self.form.deserialize(data or self.current.input['form'])

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/Pyoko-0.1-py2.7.egg/pyoko/form.py", line 57, in deserialize

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     val)

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/Pyoko-0.1-py2.7.egg/pyoko/db/base.py", line 331, in get

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     return clone._get()

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/Pyoko-0.1-py2.7.egg/pyoko/db/base.py", line 242, in _get

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     self._riak_cache[0])

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:   File "/usr/local/lib/python2.7/site-packages/Pyoko-0.1-py2.7.egg/pyoko/db/base.py", line 257, in _make_model

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]:     "GET Key: %s" % self.key

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: Exception: Returned empty data from Riak

<14>2015-09-30T11:43:26+03:00 69dd6302dbad ulakbus-11[1]: Query: -deleted:TrueGET Key: None
```

**Comment by alirizakeles** [comment]
Pyoko'da ilgili kodlar tumuyle refactor edildi. Hata tekrar edilemedi.
